gravwell/gravwell

- chancacher/filecounter.go
- chancacher/filecounter_test.go
- ingest/muxer.go
> Add guard to ingest muxer Close() method to prevent chancacher nil reference

- go.mod
- ingesters/SimpleRelay/json.go
- ingesters/SimpleRelay/simple.go
fixing ingest logging messages to remove extra newline
> fixing info message that had an extra newline on it

- ingest/boltcache.go
- ingest/boltcache_test.go
> ingest: fix cache transition edge case on empty bolt caches.

- chancacher/chancacher.go
duplication of data on next read.
> chancacher: seek/truncate before flagging close on Commit() to avoid

- go.mod
- go.sum
fixing go.mod so that we can use an updated gcfg
> bumping version on external repo

- chancacher/chancacher.go
- ingest/muxer.go
- ingest/processors/processors.go
- ingesters/winevents/build.bat
- ingesters/winevents/processing.go
- winevent/config.go
WriteContext on muxer so that we can exit even when channel is blocked
Also fixing up usage of IngestMuxer to use then new cache system.
> fixing up the windows ingester

- ingest/config/config.go
Adds environment variable configs for ingest compression, plus cache settings. Closes #41
> add environment variable config options

- ingesters/collectd/routines.go
> Make collectd properly hand around contexts so we can exit more cleanly

- ingesters/kafka_consumer/config.go
- ingesters/kafka_consumer/consumer.go
and to optionally disable Key validation
> adding options to enable TLS transports 

- ingesters/KinesisIngester/main.go
- ingesters/O365Ingester/main.go
- ingesters/PacketFleet/main.go
- ingesters/SimpleRelay/json.go
- ingesters/SimpleRelay/lineHandlers.go
- ingesters/SimpleRelay/main.go
- ingesters/SimpleRelay/rfc5424Handlers.go
- ingesters/SimpleRelay/simple.go
- ingesters/sqsIngester/main.go
> update all ingesters to use ProcessContext

- ingesters/collectd/main.go
- ingesters/kafka_consumer/consumer.go
- ingesters/networkLog/main.go
- ingesters/winevents/processing.go
> Remove references to SourceIP() and allow it to be set by ingestMuxer at write time

- ingesters/fileFollow/processing_windows.go
> add cache flags to windows file follow

- ingest/processors/gravdup.go
Previous gravwellforwarder was not properly negotiating tags.
> Fixing tag negotiation in gravwellforwarder preprocessor

- chancacher/chancacher.go
- chancacher/chancacher_test.go
> add flock to chancacher

- ingesters/GooglePubSubIngester/config.go
- ingesters/KinesisIngester/config.go
- ingesters/MSGraphIngester/config.go
- ingesters/O365Ingester/config.go
we have a generic Targets function now, we should be using it.
> fix Target function in some ingesters

- timegrinder/timeGrinder.go
- timegrinder/timeGrinder_test.go
> Adding a new global extractor for simple use

- ingest/muxer.go
> remove log message that causes deadlock

- ingesters/version/version.go
> fixing version on master

- ingest/processors/json.go
- ingest/processors/json_test.go
Leaving the Extractions parameter empty will just make it split the data instead of trying to extract a json field first.
> Allow jsonarraysplit preprocessor to split on a top-level array

- ingesters/HttpIngester/main.go
> adding some additional debug messages in verbose mode for HTTP ingester

- ingesters/version/version.go
> bumping version

- ingest/entryReader.go
This will help the Federator keep its Children up to date
> Implement callbacks for IngestState messages on the EntryReader. 

- go.mod
- go.sum
- ingest/processors/srcrouter.go
- ingest/processors/srcrouter_test.go
to figure out how to route so that we can specify CIDR too
> using radix tree 

- client/searchCtrl.go
- client/types/search.go
updating client to also be able to fire off preview mode searches, this also simplified the implementation of a few APIs
> Client API so we can fire preview searches

- ingesters/IPMIIngester/config.go
- ingesters/IPMIIngester/ipmi.conf
- ingesters/IPMIIngester/main.go
> allow multiple targets in ipmi stanza, change ipmi poll rate

- chancacher/chancacher.go
- chancacher/chancacher_test.go
> remove chancache detritus

- client/types/maps.go
> fixing map location validation

- go.mod
- go.sum
- ingest/log/logging.go
Example output from searchagent:
```
<6>1 2021-05-21T15:28:31.717243Z debug searchagent - searchagent/main.go:175 - Starting client manager
<4>1 2021-05-21T15:28:31.717483Z debug searchagent - searchagent/main.go:181 - Client Manager establish failed: Unable to connect to any webserver
<6>1 2021-05-21T15:28:46.982794Z debug searchagent - searchagent/main.go:187 - Client manager established
```
> converting logging system over to RFC5424

- client/ingest.go
- client/urls.go
- ingest/log/logging.go
cleaning up logging system to enable relays and also adding the internal ingest point
> clean up logging and make fatal logs be formatted right too

- client/types/marshallers_test.go
- client/types/search.go
Reverts gravwell/gravwell#234
We didn't want to do that after all, misunderstanding on my part.
> Revert "Implement custom marshaller for types.Element "

- client/websocketRouter/server.go
> actually send an error back if you don't request at least one subprotocol

- client/types/chart.go
Adding an IsNaN method to the ChartableDataPoint type so that we can implement the total condenser.
> adding an IsNaN method

- client/types/kits/types.go
- client/types/resource.go
adding some more methods and internal types around ResourceUpdate so that we can better stream extremely large resources
> ResourceUpdate Helpers

- client/types/resource.go
> adding close method to resource update

- ingesters/winevents/processing.go
changing the order of signaling and shutdown to see if it fixes the issue of not releasing the cache lock in time.
So apparently windows doesn't consider a service stopped when the process exits it considers it stopped when the state signal changes.  This seems entirely reasonable.  Definitely trust the signal... definitely don't actually check if the process quit.  A system service with an active process that declares itself stopped is totally ok... yep... won't be abuse... won't cause problems...
> windows service shutdown controls

- client/types/manage.go
updating marshaller to better detect empty RemoteState members
> updating the marshaller

- ingest/processors/test_data/plugins/dnslookup.go
> fixing the DNS lookup plugin

- client/types/abac.go
> fixing token API

- client/types/scheduledsearch.go
We want to store the proper error internally, but for the UI we're only going
to send a string. A quick MarshalJSON function takes care of that.
> Add a custom MarshalJSON function for FlowNodeResult.

- client/admin.go
to make it easier to completely destroy a user and all their content
> adding PurgeUser method

- client/types/license.go
- go.mod
- go.sum
- ingest/processors/regextimestamp_test.go
- ingest/processors/srcrouter.go
- ingesters/fileFollow/main_linux.go
- ingesters/fileFollow/processing_windows.go
- ingesters/version/version.go
cherry-picking in some high value dev fixes.
> prepping for 4.2.9

- ingest/processors/test_data/plugins/date_adjust.conf
- ingest/processors/test_data/plugins/date_adjust.go
some old garbage timestamps don't have dates or years, this lets you fix that by hand.
> adding preprocessor example that can force dates

- client/types/scheduledsearch.go
> Add Failures field to FlowParseResponse

- kitctl/main.go
- kitctl/pack.go
Also update the way we name automations as we unpack to apply the name given in the kit rather than the Name field, to align with the webserver behavior
> Add flow support to kitctl.

- client/types/manage.go
Also moves said function closer to the type definition for clarity.
> Add Stored field to ShardInfo MarshalJSON function.

- timegrinder/timeGrinder.go
- tools/timetester/.gitignore
- tools/timetester/README
- tools/timetester/main.go
Also adding another debug method to the timegrinder object
> adding time tester tool

- client/admin.go
- client/urls.go
Also fixing the URL and method used to Remove a user from a group, it
was broken.
Closes issues #415 and #414
> Adding in methods to work with the DefaultSearchGroup that were missing

- ingesters/winevents/processing.go
changing up the way we handle bad event stream channels and allowing the event stream readers to start when channels are missing.
This does the following:
1. Enables the ingester to start up when a defined channel is missing (at least one must exist)
2. Enables the ingester to continue functioning when a channel goes away (service uninstalled, etc...)
3. Enables the ingester to retry dead ingest streams (recover when a service comes back)
The nominal test pattern was:
1. Install ingester without sysmon
2. Configure to use sysmon
3. start ingester
4. install sysmon
5. verify that ingester detected sysmon after startup and began ingesting
6. uninstall sysmon
7. verify that ingester threw the error that the channel was gone but kept running
8. reinstall sysmon
9. verify that the ingester …
> WinEvent ingester cleanup

- client/abac.go
- client/admin.go
- client/flows.go
- client/info.go
- client/ingest.go
- client/kit.go
- client/macros.go
- client/playbooks.go
- client/resources.go
- client/scheduledSearch.go
- client/searchCtrl.go
- client/staticActions.go
Also, make putStaticURL take a recvObj argument, because PUT can return a body
> Make ConfigureMail call do a PUT instead of a POST

- ingest/processors/csvrouter.go
- ingest/processors/csvrouter_test.go
- ingest/processors/processors.go
> add csvrouter preprocessor

- client/admin.go
The backend now returns a full dashboard, not just an ID
> API: update CloneDashboard

- ingest/entryWriter.go
improving the error logging so we can better understand why configureStream sometimes gets an EOF
Should also allow for actually debugging https://github.com/gravwell/gravwell/issues/344
> improve Error logging

- client/info.go
- client/notifications.go
Organizing the notifications methods into a new file and adding the update and delete methods
Closes https://github.com/gravwell/gravwell/issues/426
> update and delete methods for notifications on the client

- .drone.yml
- client/flows.go
- client/info.go
- client/notifications.go
- client/scheduledSearch.go
- client/types/abac.go
- go.mod
- go.sum
- ingest/entryWriter.go
- ingest/log/logging.go
- ingest/processors/csvrouter.go
- ingest/processors/csvrouter_test.go
- ingest/processors/processors.go
- ingesters/version/version.go
- ingesters/winevents/main.go
- ingesters/winevents/processing.go
- migrate/.gitignore
- migrate/config.go
- migrate/files.go
- migrate/gui.go
- migrate/jobs.go
- migrate/main.go
- migrate/migrate.conf
- migrate/splunk.go
- migrate/state.go
- migrate/utils.go
Creating a flow or scheduled search/script will now return the full object in the response.
Also merges dev into api-updates.
> Fix scheduled search & flow code to be more RESTful

- ingesters/version/version.go
> Revert "bump version for 5.1.0"

- go.mod
- go.sum
- ingest/processors/persistent_buffer.go
> remove cloudflare buffer and the override and just use our internal fork

- generators/dnsmasqGenerator/.gitignore
- generators/dnsmasqGenerator/gen.go
- generators/dnsmasqGenerator/main.go
- go.mod
- go.sum
Adding new generator that mimics dnsmasq over syslog
> new dnsmasq generator

- client/types/license.go
Laying out the data structures to present license quota usage
> adding in license usage data structure

- ingesters/version/version.go
just bring version numbers up to snuff
> fixing version

- client/routingSockets.go
- client/searchCtrl.go
Cherry-picking fa3791f85698fcf125f3b5dd740530cc96404e8d
> Add the Ping() function on the Search type

- ingest/processors/cisco_ise.go
- ingest/processors/cisco_ise_test.go
- ingest/processors/jsonextract.go
- ingest/processors/jsonextract_test.go
- ingest/processors/jsonsplit.go
- ingest/processors/jsonsplit_test.go
- ingest/processors/processors.go
- ingest/processors/processors_test.go
- ingest/processors/regexextract.go
- ingest/processors/regexextract_test.go
This PR addresses https://github.com/gravwell/gravwell/issues/469
> finishing the normalization of Drop-Misses on preprocessors

- README.md
Just add the godoc badge and a link or two in the README
> add badge and some more pkg.go.dev linkages

- ingesters/SimpleRelay/config.go
- ingesters/SimpleRelay/config_test.go
- ingesters/SimpleRelay/rfc5424Handlers.go
- ingesters/SimpleRelay/rfc6587Handlers.go
- ingesters/SimpleRelay/simple.go
Also implements a max payload on the readers of 100KB, which is WAY WAY over what the RFCs hint at
This PR addresses https://github.com/gravwell/gravwell/issues/484
This PR addresses https://github.com/gravwell/gravwell/issues/483
> SimpleRelay RFC6587 reader type

- ingesters/fileFollow/WixUI_HK.wxs
- ingesters/fileFollow/en-us.wxl
- ingesters/winevents/WixUI_HK.wxs
- ingesters/winevents/en-us.wxl
addresses issue https://github.com/gravwell/gravwell/issues/512
we disable the change and repair buttons now.
> disabling the change and repair buttons in MSI installers

- go.mod
- go.sum
- ingesters/O365Ingester/config.go
- ingesters/O365Ingester/main.go
and adding ability to se the o365 Plan in the config
> using a gravwell maintained repo for the o365 lib 

- ingesters/KinesisIngester/main.go
- ingesters/PacketFleet/main.go
- ingesters/SimpleRelay/main.go
- ingesters/collectd/main.go
- ingesters/kafka_consumer/main.go
- ingesters/netflow/main.go
- ingesters/networkLog/main.go
- ingesters/sqsIngester/main.go
removing cpu and memory profile flags for production ingesters
> removing the cpu and memory profiling of ingesters

- ingesters/s3Ingester/.gitignore
- ingesters/s3Ingester/bucket.go
so it handles things better and stores the state more intelligently
This PR addresses https://github.com/gravwell/gravwell/issues/551
> fixing up bucket ARN/URL/Name logic 

- ingesters/s3Ingester/bucket.go
- ingesters/s3Ingester/s3.conf
left in backwards compatability
This PR addresses https://github.com/gravwell/gravwell/issues/553
> changing Bucket-URL to Bucket-ARN to clarify, 

- ingest/processors/jsontimeextract.go
- ingest/processors/jsontimeextract_test.go
- ingest/processors/processors.go
This PR addresses https://github.com/gravwell/gravwell/issues/523
> adding json timestamp extraction preprocessor

- client/admin.go
Backups can take some time to generate, our OG client times out after 5s.
This implements a custom client on that method so that we timeout quickly on connection, but then wait up to 5 minutes to complete a backup.
> Backup timeout

- ingesters/HttpIngester/main.go
- ingesters/IPMIIngester/main.go
- ingesters/PacketFleet/main.go
- ingesters/SimpleRelay/main.go
- ingesters/collectd/main.go
- ingesters/networkLog/main.go
nothing fatal, just beep so we have better logging when things fail.
> adding capability checks at startup to ingesters that may need them

- client/types/scheduledsearch.go
This will help us give more detailed error logging if something goes wrong.
> Add some fields to the FlowNodeResult type

- client/types/chart.go
adding a new sorting method in a chartable so that we can control series order a little more intelligently on some cases
> adding some helpers on chartables

- generators/gravwellGenerator/sysloggen.go
> fixing my fix

- generators/windowsEventGenerator/gen.go
- ingest/log/stderrlog_unix.go
- ingesters/AzureEventHubs/main.go
- ingesters/GooglePubSubIngester/main.go
- ingesters/HttpIngester/main.go
- ingesters/IPMIIngester/main.go
- ingesters/KinesisIngester/main.go
- ingesters/MSGraphIngester/main.go
- ingesters/O365Ingester/main.go
- ingesters/Shodan/main.go
- ingesters/SimpleRelay/main.go
- ingesters/collectd/main.go
- ingesters/fileFollow/main_linux.go
- ingesters/kafka_consumer/main.go
- ingesters/netflow/main.go
- ingesters/networkLog/main.go
change Dup2 to Dup3 so we can compile on ARM and ARM64
> Dup2->Dup3

- ingest/processors/corelight.go
- ingest/processors/corelight_data_test.go
- ingest/processors/corelight_test.go
so... corelight JSON can contain tabs...
> adding some logic to clean tabs out of data before encoding into TSV

- client/info.go
> add methods to delete a mail configuration

- go.mod
- go.sum
> remove replace directive for msgraph library

- ingest/entry/entry.go
- ingest/entry/entry_test.go
> fixing EntrySize helper

- ingesters/s3Ingester/bucket.go
- ingesters/s3Ingester/config.go
- ingesters/s3Ingester/main.go
- ingesters/s3Ingester/utils.go
FYI: *S3 compatible* is like saying *PC compatible*....
Docs coming soon.
Fixes issue #559
> Issue559 - alternate endpoints and schemes on S3

- ingesters/SimpleRelay/jsonConfig.go
This PR addresses https://github.com/gravwell/backend-issues/issues/4956
> fixing weird logic that was trying to dedup extractors

- client/secrets.go
- client/urls.go
UpdateSecret changes the value. UpdateSecretDetails changes everything else.
> split the secret updating apis into two

- client/types/secrets.go
It should be "created" not "createdAt".
> Change json name of Created field in secrets.

- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/hec_config.go
- ingesters/SimpleRelay/json.go
- ingesters/utils/jsonreader.go
- ingesters/utils/jsonreader_test.go
> HEC-Compatible-Listener fixes

- ingesters/snmp/main.go
I was overwriting changes to gosnmp.Default, this fixes that. Also makes sure we don't drop on MsgFlags unless it's v3.
> fix pointer silliness

- client/types/host.go
- client/types/stats.go
- ingest/api.go
- ingest/entryWriter.go
- ingest/muxer.go
last seen to make tracking missing ingesters easier as per customer request
Also adding IDs to disk stats to track similar disk/mount stats across multiple indexers
also adding helper to search module stats.
> adding some new members to types that we need

- generators/gravwellGenerator/consts.go
- generators/gravwellGenerator/main.go
- generators/gravwellGenerator/xmlgen.go
just adding an XML generator for testing
> XML generator

- .github/workflows/golang-testing.yml
> trying to do mono repo testing using github actions

- ingest/processors/regexextract.go
- ingest/processors/regexextract_test.go
fixing discussed regexextract preprocessor behavior
> adding attach logic for cisco garbage

- client/admin.go
- client/types/backup.go
The new BackupWithConfig function takes a BackupConfig object which lets you specify more options:
* Omit "sensitive" data (secrets, tokens, email configs)
* Encrypt with a password
The RestoreEncrypted function restores a backup that has been encrypted with a password.
> Enhance backup and restore functionality.

- client/types/abac.go
This PR proposes adding a "Category" field to the CapabilityDesc type.
> Add Category to CapabilityDesc

- client/info.go
- client/resources.go
oops, got over-eager on the last PR
> remove duplicate defs

- ingesters/SimpleRelay/jsonConfig.go
> fix mistake in jsonlistener Tags function

- ingesters/SimpleRelay/jsonConfig.go
> dedup tags

- .github/workflows/golang-testing.yml
- go.sum
Adding some tests to make sure our go.mod and go.sum files are validated and clean.
> adding some more steps and cleaning up the go.mod file

- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/hec_config.go
> track HEC IDs per request ID

- ingest/entry/enumerated_types.go
this is  for efficiently converting from types.StringTagEntry
> add a new method to assign directly into an enumerated data item

- ingest/ingestConnection.go
- ingest/processors/syslogrouter.go
- ingest/processors/syslogrouter_test.go
- ingest/simple.go
- ingest/utils.go
- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/hec_config.go
- ingesters/HttpIngester/kinesisdeliverystream.go
- ingesters/IPMIIngester/config.go
- ingesters/PacketFleet/config.go
- ingesters/SimpleRelay/config.go
- ingesters/args/args.go
- ingesters/canbus/config.go
- ingesters/collectd/config.go
- ingesters/diskmonitor/main.go
- ingesters/fileFollow/config.go
- ingesters/massFile/main.go
- ingesters/netflow/config.go
- ingesters/networkLog/config.go
- ingesters/s3Ingester/config.go
- ingesters/session/main.go
- ingesters/snmp/config.go
- ingesters/sqsIngester/config.go
- migrate/files.go
- winevent/config.go
> fixing tag checking

- client/types/search.go
- client/urls.go
more stuff for REST search control
> adding in URLs and updating types

- ingesters/fileFollow/build.bat
- ingesters/fileFollow/product.wxs
- ingesters/winevents/build.bat
we weren't drilling deep enough into the config directory to detect the existing config.
> updating versions and fixing existing install detection on file follower

- ingesters/fileFollow/build.bat
- ingesters/fileFollow/product.wxs
- ingesters/winevents/build.bat
cherry-picking hotfix out of dev
> updating verisons and fixing existing install detection on file follower

- client/types/search.go
- ingesters/fileFollow/build.bat
- ingesters/fileFollow/product.wxs
- ingesters/winevents/build.bat
update search preview store with master and dev
> Update Preview/search store with master and dev

- client/admin.go
- client/urls.go
> adding method to forget an ingester from our state tracker

- filewatch/filewatch_test.go
- ingest/muxer.go
This PR addresses https://github.com/gravwell/gravwell/issues/679
> Emit version when ingester goes hot

- filewatch/filters.go
- filewatch/followers.go
This PR addresses https://github.com/gravwell/gravwell/issues/668
> make the catchup functions also check for and deal with data missing a termination value

- client/abac.go
- client/types/abac.go
- client/types/abac_templates.go
- client/types/abac_test.go
- client/urls.go
> moving to new ABAC model

- ingesters/HttpIngester/hec.go
The docs indicate that you should send back a JSON response message with status codes etc. We weren't doing that because everything we'd tested with thus far was happy with just HTTP status codes, but some things are looking for a proper response.
@kris-watts-gravwell If you can build this and try it out yourself before we merge, I'll feel a lot better about the change. It shouldn't affect anything, since it's just adding a response body where previously there was none, but who knows.
> Add JSON responses to HEC listeners

- client/cbac.go
- client/client.go
> adding HasCap for issue #720

- client/types/license.go
> Revert "add CBAC flag to license info struct"

- client/urls.go
Finally finished tests on the backend side so hopefully it's all shaken out now. Sorry for the churn.
> Another typo

- ingest/entry/enumerated.go
- ingest/entry/enumerated_types.go
- ingesters/reimport/main.go
- ingesters/utils/readers.go
make it capable of reimporting EVs too
> add some more functionality to the reimport ingester

- .github/workflows/golang-testing.yml
- go.mod
- go.sum
bumping go version in CI/CD tests and compress lib verson
> bump go version and compress version

- client/admin.go
- client/client.go
- client/info.go
- client/kit.go
- client/resources.go
- client/staticActions.go
- client/userfiles.go
- client/utils.go
> adding a proper HTTP response draining function

- client/staticActions.go
If there was a non-200 response, the Client functions will return a ClientError, which contains the status code and body of the error message returned. This makes it easier to test what failed, rather than doing string matching.
> Improve errors returned by the client

- .github/workflows/golang-testing.yml
- ingest/processors/json_filter_test.go
- ingest/processors/jsonextract.go
- ingest/processors/jsonextract_test.go
- ingest/processors/jsonfilter.go
- ingest/processors/jsonsplit.go
- ingest/processors/jsonsplit_test.go
- ingest/processors/jsontimeextract.go
- ingest/processors/jsontimeextract_test.go
> add support for quoted json fields when wrapped in raw quotes.

- ingesters/AzureEventHubs/main.go
- ingesters/GooglePubSubIngester/main.go
- ingesters/IPMIIngester/main.go
- ingesters/KinesisIngester/main.go
- ingesters/MSGraphIngester/main.go
- ingesters/O365Ingester/main.go
- ingesters/PacketFleet/main.go
- ingesters/base/base.go
- ingesters/collectd/main.go
- ingesters/fileFollow/main_linux.go
- ingesters/kafka_consumer/main.go
- ingesters/netflow/main.go
- ingesters/networkLog/main.go
- ingesters/sqsIngester/main.go
> wire in file rotation for ingester logs

- ingesters/fileFollow/config.go
- ingesters/fileFollow/main_linux.go
- ingesters/fileFollow/main_windows.go
adding dump state flag to file follower so its easier to inspect the state
This PR addresses https://github.com/gravwell/gravwell/issues/780
> FileFollow -dump-state flag to dump state file in human readable form

- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/main.go
- ingesters/collectd/config.go
- ingesters/collectd/main.go
- ingesters/fileFollow/config.go
- ingesters/fileFollow/main_linux.go
- ingesters/netflow/config.go
- ingesters/netflow/main.go
Adding
- linux file follow
- collectd
- netflow
- HTTP ingester
> more boilerplate work

- ingest/processors/jsonextract.go
- ingest/processors/jsontimeextract.go
- ingest/processors/jsontimeextract_test.go
it works just fine, here are tests to prove it
This PR addresses #769
> adding tests and removing a debug statement

- .github/workflows/golang-testing.yml
- ingest/attach/attach.go
- ingest/muxer.go
- ingesters/fileFollow/config.go
- ingesters/fileFollow/main_windows.go
- ingesters/fileFollow/processing_windows.go
- ingesters/winevents/config.go
- ingesters/winevents/main.go
- ingesters/winevents/processing.go
- winevent/utils.go
- winevent/winevent.go
This PR does the following:
1. make the Attach config marshal JSON correctly
2. Windows events and file follower now support attach configs
3. Windows file follower report its config
This PR addresses https://github.com/gravwell/gravwell/issues/783
> Windows Attach work

- ingest/config/setingesteruuid_windows.go
this is already fixed in dev, just pulling it into master too
> fixing windows implementation of the setIngesterUUID function

- .github/workflows/golang-testing.yml
This PR addresses [ISSUE_LINK]
> removing restrictions on branchs

- .github/workflows/golang-testing.yml
- ingesters/version/version.go
release version to 5.3.4 and go version to 1.20.7
> bumping versions

- .github/workflows/golang-testing.yml
- go.mod
- go.sum
> bringing in updated ipfix module

- ingesters/HttpIngester/hec.go
add http ingester type to deal with all the craziness that can show up in an "Event"
This closes issue https://github.com/gravwell/gravwell/issues/805
> HTTP Detect Event Body Type

- ingesters/AzureEventHubs/main.go
- ingesters/GooglePubSubIngester/main.go
- ingesters/HttpIngester/main.go
- ingesters/IPMIIngester/main.go
- ingesters/KinesisIngester/main.go
- ingesters/MSGraphIngester/main.go
- ingesters/O365Ingester/main.go
- ingesters/PacketFleet/main.go
- ingesters/SimpleRelay/main.go
- ingesters/base/base.go
- ingesters/collectd/main.go
- ingesters/kafka_consumer/main.go
- ingesters/netflow/main.go
- ingesters/networkLog/main.go
- ingesters/s3Ingester/main.go
- ingesters/snmp/main.go
- ingesters/sqsIngester/main.go
make ingesters announce version and info at startup
> startup and shutdown announcement

- generators/gravwellGenerator/sysloggen.go
> Make generator do random BOM and UTF-8 on syslog

- ingesters/HttpIngester/hec.go
This pull request closes issue https://github.com/gravwell/gravwell/issues/824
> making the HEC ingester ignore completely empty things

- ingesters/AzureEventHubs/main.go
- ingesters/GooglePubSubIngester/main.go
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/main.go
- ingesters/netflow/main.go
- ingesters/networkLog/main.go
- ingesters/s3Ingester/bucket.go
- ingesters/s3Ingester/sqss3.go
- ingesters/snmp/main.go
> fixup remaining ingesters to use cancel contexts where needed.

- client/types/event.go
This will enable better logging
> add Level field to EventLog struct

- ingesters/base/base.go
This PR fixes issue https://github.com/gravwell/gravwell/issues/847
> fix config registration not showing ingesters

- ingest/processors/plugin/packages.Scriggofile
- ingest/processors/plugin/packages.go
this package is awful anyway, not to mention it should not even be in these plugins.
> remove ms-graph package from plugins

- .github/workflows/golang-testing.yml
just bumping actions lib versions
> update actions to V4 stuffs

- .github/workflows/golang-testing.yml
- ingest/processors/processors.go
- ingesters/HttpIngester/auth.go
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/hec_config.go
- ingesters/HttpIngester/kinesisdeliverystream.go
- ingesters/HttpIngester/main.go
- ingesters/utils/jsonreader.go
allow for a new flag to debug POSTs on HEC ingester
Also fix some weirdness on high load preprocessors
> fixing HEC and preprocessor stuff

- generators/base/base.go
- generators/base/raw.go
> add UDP output on generator

- filewatch/followers.go
and recovering when lines get written really really slowly or in mass batches with long wait times.
> fixing up file follower 

- client/alerts.go
- client/flows.go
Forgot to fixup a few usages of client methods
> fix interface changes

- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/hec_config.go
- ingesters/HttpIngester/main.go
'
This PR addresses https://github.com/gravwell/gravwell/issues/916
> adding ability to specify URL parameters that are attached to EVs on routes

- migrate/splunk.go
- migrate/splunkconn.go
We previously just tried to find chunks of N entries or less. Now we also try to stay under M megabytes (800, because we've seen limits of 1GB for a single query in some situations). Tracks average size of entries seen so far in order to estimate how big the chunk will be, because tstats doesn't keep track of entry sizes, just counts. Because of this, we now start with a 1 minute chunk so we can get spun up quick and estimate entry sizes sooner than later, in order to expand our window if possible.
Also prints out more useful information if the job runs into unexpected results; often as not, it's Splunk spitting back XML because you've exceeded some quota.
> Attempt to make the Splunk job more intelligent

- ingest/attach/attach.go
- ingest/attach/attach_test.go
This PR addresses https://github.com/gravwell/gravwell/issues/933
> Add ability to attach environment variables on ingesters too

- .github/workflows/golang-testing.yml
- ingesters/s3Ingester/decode_test.go
- ingesters/s3Ingester/manager.go
Cherry pick the S3 ingester fixes into master
> Add additional decode format and tests for sns/s3 decoder. (#937)

- generators/gravwellGenerator/jsongen.go
- generators/gravwellGenerator/main.go
new generator type that can flex all the craziness when records are huge.
> add new mega JSON data type to gravwell generator

- client/client.go
provide functions to be able to add and delete items from our query and header maps.
> adding some additional functions on our client to enable debugging and testing

- .github/workflows/golang-testing.yml
- ingesters/HttpIngester/hec.go
Add time to process in debug posts log message so that we can identify posts that are sucking.
> Add time to process POST in `Debug-Posts` log entry.  We going straight to ms.

- generators/base/base.go
- generators/base/hec.go
- ingesters/HttpIngester/main.go
- ingesters/utils/profile.go
we can use this profile thingy to include in all ingesters, it makes everything cleaner
> adding generator chaos mode and adding some profiling systems

- generators/base/base.go
- generators/base/hec.go
allows workers on the chaos HEC single line ingester
> Adding some more chaos factors to gravwellGenerator

- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/main.go
Just some additional safety stuff to maximize the likelihood that we will get to perform socket reuse and also make sure that the Http server shuts down gracefully without terminating connections.
> HTTP Ingester cleanup

- client/types/render.go
> fixing marshaller on stats

- ingesters/s3Ingester/manager.go
> s3/sqs ingester: delete messages in the same batch as we receive.

- generators/base/hec.go
- ingest/config/config.go
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/main.go
- ingesters/base/base.go
- ingesters/utils/stats.go
> ingest metrics for HTTP ingester

- ingesters/utils/stats.go
> fixing stats system to only throw if we actually have stats

- ingest/muxer.go
PLEASE review carefully, reconnect logic changes are scary
> make ingester reconnects backoff for all cases and also back off exponetially

- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/hec_config.go
because there are no rules apparently
This PR addresses https://github.com/gravwell/gravwell/issues/988
> add ability to specify Authorization token name

- ingest/config/validate/validate.go
- ingest/processors/plugin/packages.go
- ingest/processors/plugin/packages_windows.go
just add some clarity to the log
> make logging a little better

- ingesters/s3Ingester/bucket.go
- ingesters/s3Ingester/manager.go
- ingesters/sqsIngester/main.go
- sqs_common/sqs.go
fix depth and retry on deletes
> fixing queue depth on S3 ingester

- ingesters/s3Ingester/bucket.go
- ingesters/s3Ingester/manager.go
- ingesters/s3Ingester/utils.go
Covers: https://github.com/gravwell/gravwell/issues/1000
> adding some more logging to the S3 ingester

- .github/workflows/golang-testing.yml
- go.mod
- ingesters/version/version.go
just getting the preview/search-store up to date
> Preview/search store: bump to v4, bump go module version

- ingesters/HttpIngester/hec.go
This PR addresses https://github.com/gravwell/gravwell/issues/1009
> address issue #1009, zero timestamps in HEC structured value

- client/types/search.go
reduce API stress by giving more fields on search ctrl status list
> add some fields to searchctrl status

- ingesters/HttpIngester/amazon_firehose.go
- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/gravwell_http_ingester.conf
- ingesters/HttpIngester/main.go
> rename kinesis data stream to amazon firehose

- ingest/muxer.go
> don't flush on reschedules for load balancing.

- .github/workflows/golang-testing.yml
- go.mod
- go.sum
- ingest/gravwell_log.go
This PR addresses [ISSUE_LINK]
> KAAAAAAAHN!   vluns in stdlib AND google protobuf, which is fun.

- ingest/muxer.go
- ingesters/HttpIngester/handlers.go
> Return 507 if the ingester can't write to the indexer or cache.

- filewatch/followers.go
> Fix logic on fsnotify Removed events.

- ingest/muxer.go
If an ingest connection isn't running, it's very much a non-issue, so throw an info log and move on.
Other errors get a warning, but it's still not a big deal.
Addresses #981
> Improve error logging on NegotiateTag

- ingesters/version/version.go
> just bumping version prepping for 5.4.8 release branch

- client/searchCtrl.go
> adding Close method directly on the search object

- client/searchCtrl.go
- client/staticActions.go
> populating search object on attach

- client/searchCtrl.go
- client/types/maps.go
implementing all the APIs for retrieving data for all the various renderers using REST calls.
> working on client API stuff for preview/search-store

- filewatch/filters.go
> Save backup and create new state file in filefollower when the state file is unreadable

- ingesters/HttpIngester/handlers.go
basically check the willBlock call on the health check too
> throw the insufficient storage head on the health check if the cache is full

- client/scheduledSearch.go
- client/types/api.go
Get when the searchagent last checked in.
> Add GetSearchAgentCheckin function

- client/client.go
- client/mfa.go
- client/types/api.go
- client/types/users.go
- client/urls.go
Warns user if MFA is required, allows user to set up TOTP MFA, and adds function to log in with MFA/TOTP.
> Add basic TOTP functionality

- migrate/config.go
just fixes validate flag on migrate tool.
> fixing validate flag on migrate

- client/types/users.go
We'll ship information about what's enabled, but leave out the sensitive stuff.
> Improve handling of MFA in UserDetails

- client/types/users.go
This way we can track which users are created/managed via SSO.
> Add SSOUser field to UserDetails struct

- filewatch/filewatch.go
- filewatch/filewatch_test.go
This PR addresses https://github.com/gravwell/gravwell/issues/1004
> address issue #1004 by letting file follower start if a folder does not exist, it will get picked up later

- .github/workflows/golang-testing.yml
- client/types/alert.go
If IngestBlocked is true, the owner of the alert is not allowed to ingest data (events will not be recorded)
> Add a field to alerts indicating if the events will ingest

- ingest/muxer.go
bring in the entryReader/entryWriter close timeouts
> 5.4.11 -> Dev

- client/types/stats.go
Tracks how many bytes of scratch have been written
> Add field to ModuleStatsUpdate

- ingest/entryReader.go
this is me... this is my shameful crown to wear.
> remove stupid entCache on entryReader

- generators/gravwellGenerator/consts.go
- generators/gravwellGenerator/jsongen.go
- ingest/muxer.go
Also add some IPv6 variability to the generator
This PR addresses no issue
> Do not instantly timeout on a muxer.Sync() if the timeout is zero

- ingesters/kafka_consumer/config.go
- ingesters/kafka_consumer/consumer.go
This PR addresses https://github.com/gravwell/gravwell/issues/1145
> fixing kafka ingester to support multiple kafka bootstrap leaders

- go.mod
- go.sum
- ingest/processors/plugin/packages.Scriggofile
- ingest/processors/plugin/packages.go
- ingest/processors/plugin/packages_windows.Scriggofile
- ingest/processors/plugin/packages_windows.go
- ingest/processors/plugin/plugin_progs_test.go
remove it from go.mod and go.sum and just alias the package name to ours in scriggo
> remove the buger json parser entirely

- .github/workflows/pr-labels.yml
- .github/workflows/sync-branches.yml
This PR proposes adding workflows to automate...
- application of behind/conflict labels to PRs
- Improves visiblity
- opening/updating PRs to next-* and preview/*/* branches
- Housekeeping
> ci: Add label and sync workflows

- client/types/search.go
- client/types/searchlog.go
This will allow us to share search results with a list of groups or globally, same as just about everything else in the system.
> Add some fields to improve sharing of searches

- .github/workflows/golang-testing.yml
- .github/workflows/local_run.sh
- go.mod
all the local stuff passes, lets get this rolling to find any other issues with the new iterator stuff.
> updating to 1.23.0 for preview/major branch

- .github/workflows/golang-testing.yml
this pr addresses no issue.
No reason to run the tests on a merge, only on a pull request
> remove golang test runs on merges

- client/types/users.go
adding a method and cleaning up the logic so we don't fire on Zero at all
> ignored method on notifications and simplify logic

- ingesters/collectd/routines.go
don't puke on JSON encode errors because JSON can't encode many float64's
> check values and omit anything that cannot be encoded in JSON

- ingesters/base/base.go
This PR does not address any issues
> base.go: Fix error dialogue typos

- ingest/processors/processors.go
- timegrinder/timeGrinder_test.go
> adjust comment

- client/types/license.go
- ingest/processors/plugin/plugin.go
- ingest/processors/plugin_test.go
- ingest/processors/processors.go
- ingest/processors/test_data/plugins/crash.go
- ingesters/version/version.go
- timegrinder/timeGrinder_test.go
Just adding in free tier stuff
> Next minor

- client/types/license.go
> fixing boolean i missed

- client/types/license.go
> adding in cloud license tier and remote AI feature sets

- go.mod
- go.sum
- ingest/processors/syslogrouter_test.go
This PR addresses https://github.com/gravwell/gravwell/issues/1248
> brining in fix to syslog parser and adding more tests

- ingesters/version/version.go
This PR addresses no issue, it just brings 5.5.6 into main
> v5.5.6 -> main

- filewatch/filters.go
- filewatch/followers.go
- filewatch/reader.go
- filewatch/reader_windows.go
Reverts gravwell/gravwell#1296
> Revert "clean up some more state operations and make failures across multiple overlapping filters not affect other filters"

- filewatch/filters.go
> track renames correctly regardless of event order

- filewatch/followers.go
> Do a final call to processLines on the way out of a file follow

- generators/base/base.go
- generators/gravwellGenerator/consts.go
- generators/gravwellGenerator/gen.go
- generators/gravwellGenerator/main.go
- go.mod
- go.sum
This is just cleaning up the robot PR, so use this insead of this:
https://github.com/gravwell/gravwell/pull/1337
> `next-patch` -> `next-minor`

- generators/gravwellGenerator/gen.go
> remove debug print

- client/types/cbac.go
> Adding in some additional CBAC controls

- client/types/host.go
> adding in deployment info for AI stuff

- client/types/cbac.go
Need to fix wording and strings.
> cleaning up wording and making it consistent on AI capablities

- ingest/api.go
- ingest/muxer.go
deal with ingesters (namely federators) that have WAY too much state
this will first try to trim configs and metadata
then it will trim children
then it will give up and throw a log
> Make ingesters not even try to write a state if its too large

- ingest/processors/jsonextract.go
- ingest/processors/processors_test.go
If we are doing drop misses or strict extraction, pre-validate that we even have a JSON object.
This PR addresses https://github.com/gravwell/gravwell/issues/1036
> Address Issue 1036

- ingesters/version/version.go
> bump versions for hotfix

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/customer_request.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/task.md
> Task: Update issue templates

- ingest/entry/enumeratedblock.go
- ingest/entry/enumeratedblock_test.go
we were allowing a header to be assigned when adding empty slices.
> fix a failure to detect and handle encoding and adding empty enumerated value slices

- client/types/ai.go
The type proposed in this PR supports the implementation of a new AI healthcheck API.
> feat: Add AI healthcheck type

- client/types/ai.go
> adding new member

- ingest/muxer.go
so that blocked writes fail immediately and we do a little better at cleanup with the cache on
This PR makes the following changes:
1. blocked writes fail immediately on muxer shutdowns
2. shutdowns when the cache is active will take some better care to try to get data into the cache
3. Close no longer sleeps, instead we rely on cache and cleanup logic
This PR addresses https://github.com/gravwell/gravwell/issues/1455
> fixing up some of the shutdown logic

- ingest/entryWriter.go
- ingest/ingestConnection.go
- ingest/muxer.go
This PR addresses no issue, just cleanup
> address weird comment and ignored error

- ingesters/version/version.go
> bump version

- ingest/muxer.go
Muxer will refuse to connect to any indexer reporting an API version lower than that specified in the config, thus if you intend to use ditto you might say:
igCfg := ingest.UniformMuxerConfig{
[...]
MinVersion:         ingest.MINIMUM_DITTO_VERSION,
[...]
}
igst, _ = ingest.NewUniformMuxer(igCfg)
An insufficient API version is treated as non-fatal; the muxer will attempt to reconnect to that indexer periodically, on the assumption that it will eventually be updated.
As long as one indexer meets the minimum version requirement, you will be able to use the muxer as usual. If not, the muxer will never go hot.
> Add MinVersion field to muxer configs.

- generators/gravwellGenerator/main.go
- ingest/simple.go
This PR addresses https://github.com/gravwell/gravwell/issues/1504
> set timeout on ingester authentication

- client/types/ai.go
> adding another field for AI health check API

- ingesters/version/version.go
> 5.6.9 to main

- client/types/host.go
just adding a field, This PR addresses no specific issue.
> add AIDisabledReason

- .github/workflows/golang-testing.yml
- client/mfa.go
- client/types/cbac.go
- client/types/cbac_templates.go
- client/types/host.go
- client/types/license.go
reduce ambiguity on where the AI processors live
This PR addresses  no specific issue.
*NOTE* there was a govet issue in the `client/mfa.go` file, so I fixed that too.
> change the RemoteAI stuff to just LogbotAI 

- client/types/host.go
This PR addresses no issue, just adding more info into deployment info API
> adding renderstorelimit in deployment info

- generators/gravwellGenerator/consts.go
> fix consts count overrides so we don't panic when seeding, issue #1536

- ingesters/AzureEventHubs/main.go
- ingesters/GooglePubSubIngester/main.go
- ingesters/KinesisIngester/main.go
- ingesters/MSGraphIngester/main.go
- ingesters/O365Ingester/main.go
- ingesters/s3Ingester/config.go
- ingesters/winevents/processing.go
These are the low-hanging fruit
See gravwell/gravwell#1416
> Implement timestamp window handling for some ingesters

- filewatch/handler.go
- ingesters/SimpleRelay/json.go
- ingesters/SimpleRelay/lineHandlers.go
- ingesters/SimpleRelay/regexHandlers.go
- ingesters/SimpleRelay/rfc5424Handlers.go
- ingesters/SimpleRelay/rfc6587Handlers.go
- ingesters/SimpleRelay/simple.go
- ingesters/fileFollow/main_unix.go
- ingesters/fileFollow/processing_windows.go
- ingesters/kafka_consumer/config.go
> Add timestamp window capability to filefollow, simple relay, kafka

- filewatch/handler.go
- ingesters/SimpleRelay/json.go
- ingesters/SimpleRelay/lineHandlers.go
- ingesters/SimpleRelay/regexHandlers.go
- ingesters/SimpleRelay/rfc5424Handlers.go
- ingesters/SimpleRelay/rfc6587Handlers.go
- ingesters/SimpleRelay/simple.go
- ingesters/fileFollow/main_unix.go
- ingesters/fileFollow/processing_windows.go
- ingesters/kafka_consumer/config.go
- ingesters/version/version.go
> next-major -> Preview/major/search store

- client/types/api.go
- ingest/config/config.go
- ingest/log/utils.go
Adding in UDP logging target stuff for all ingesters
> Udp logger for all ingesters

- ingesters/s3Ingester/sqss3.go
> populate default max line size in sqs listener

- ingest/entry/entry.go
- ingest/entry/enumerated_test.go
- ingest/entry/enumerated_types.go
- ingest/entry/enumeratedblock.go
> Add JSON marshal and umarshal support to our native types

- debug/debug.go
> a little abstraction on Debug handlers so we can use them in other components

- .gitignore
- experiments/gravwell_fetcher/README.md
- experiments/gravwell_fetcher/asana.go
- experiments/gravwell_fetcher/asanaConfig.go
- experiments/gravwell_fetcher/duo.go
- experiments/gravwell_fetcher/duoConfig.go
- experiments/gravwell_fetcher/fetcherConfig.go
- experiments/gravwell_fetcher/gravwell_fetcher.conf.example
- experiments/gravwell_fetcher/main.go
- experiments/gravwell_fetcher/okta.go
- experiments/gravwell_fetcher/oktaConfig.go
- experiments/gravwell_fetcher/shodan.go
- experiments/gravwell_fetcher/shodanConfig.go
- experiments/gravwell_fetcher/statetracker.go
- experiments/gravwell_fetcher/thinkst.go
- experiments/gravwell_fetcher/thinkstConfig.go
- ingesters/version/version.go
> `next-major` -> `preview/major/search-store`

- client/types/license.go
> adding SSO allowed on all license types

- ingesters/version/version.go
> bump versions

- ingest/processors/processors.go
- ingest/processors/tagSrcRouter.go
First pass of the TagSrcRouter preprocessor,
It still needs:
> first pass of tag src router preprocessor

- ingest/processors/tagSrcRouter.go
- ingest/processors/tagSrcRouter_test.go
Add unit test for tagRouter.
https://github.com/gravwell/gravwell/pull/1698
Take 2
> Add unit test. Change breaks to continues.

- ingesters/base/base.go
This PR addresses and internal issue.
> update base ingester system to emit the UUID of the ingester if it exists and we are redirecting STDERR

- experiments/gravwell_fetcher/README.md
- experiments/gravwell_fetcher/fetcherConfig.go
- experiments/gravwell_fetcher/main.go
- experiments/gravwell_fetcher/mimecast.go
- experiments/gravwell_fetcher/mimecastConfig.go
- experiments/gravwell_fetcher/thinkst.go
- go.mod
- go.sum
this just brings next-minor into next-major
> `next-minor` -> `next-major`

- ingesters/AzureEventHubs/main.go
> add some logging about consumer group on Azure Event Hubs

- client/admin.go
- client/macros.go
- client/types/assets.go
- client/urls.go
- gwcli/connection/connection_test.go
- gwcli/script_test.go
- gwcli/tree/macros/macros.go
This rounds out the basic interface I expect to have for *every* asset type going forward.
> Implement PurgeMacro and CleanupMacros, plus ListMacros options

- client/searchCtrl.go
This PR just fixes a client request to unmarshal into the correct new type.
> Small fix to client request

- client/searchCtrl.go
- client/types/render.go
- client/types/stats.go
Just getting next-major merged up
> `next-major` -> `preview/major/results`

- client/types/kits/types.go
Addresses gravwell/issues#1559 by allowing kits to include scheduled searches which reference the search library.
> Add SearchReference to PackedScheduledSearch type

- client/info.go
- client/types/manage.go
- client/urls.go
> Add SearchQueue type

- client/searchCtrl.go
- client/urls.go
Addresses gravwell/issues#1795
> add client calls for searchistory/all endpoint

- go.mod
- go.sum
> update syslogparser package

- client/info.go
- client/types/manage.go
- client/urls.go
- go.mod
- go.sum
Merge next-major into registry
> Major to registry sep8

- client/admin.go
- client/macros.go
- client/types/search.go
- gwcli/script_test.go
- gwcli/tree/macros/macros.go
We're going to do this for all assets, because it makes pagination possible.
> Make a list request on macro endpoints return a MacroListResponse.

- client/admin.go
- client/tokens.go
- client/types/api.go
- client/types/cbac.go
- client/types/search.go
> Make the tokens API return a struct when listingr

- timegrinder/processors.go
- timegrinder/timeGrinder.go
- timegrinder/timeGrinder_test.go
> Add the Gravwell date picker format to timegrinder
