- ingest/entryWriter.go
- ingest/entryWriter_test.go
- ingest/ingestConnection.go
- ingest/muxer.go
- ingesters/kafka_consumer/config_test.go
- ingesters/kafka_consumer/consumer.go
- ingesters/kafka_consumer/kafka.conf
fixing issue where muxer could build up a list of entries and resend them, potentially even corrupting tag assignments when an ingest connection repeatedly bounces while under high load
> muxer bouncing and tag corruption

- ingesters/kafka_consumer/kafka.conf
Our shell installers expect a particular format so they can re-write the config files during installation. This change enables that.
Fixes #19
> fix #19 by modifying default kafka ingester config

- ingest/boltcache.go
- ingest/boltcache_test.go
- ingest/muxer.go
@floren the only code in boltcache.go that needs review is `boltTranstition()`, the rest of that file is the old cache. 
The idea here is to trigger on someone pointing neucache to a regular file, which we assume to be an old cache. We attempt to translate it to neucache in place, and just carry on.
> ingest: add transition stub from old boltdb cache to neucache

- ingesters/PacketFleet/main.go
> packetfleet: don't leak jobs on invalid queries

- ingesters/PacketFleet/main.go
there was a debug print when failing to load a config file.
> removing debug print

- go.mod
- go.sum
- ingest/processors/json.go
- ingest/processors/json_test.go
- ingest/processors/processors.go
JSONARRAY preprocessor now supports an `Additional-Fields` argument that lets you pack along some more stuff when cracking apart arrays.
> adding an additional operator on the jsonarraysplit preprocessor

- ingest/processors/forwarder.go
It was ignoring the filtering logic when filtering on tags.
> Fixing bug in forwarder preprocessor

- ingest/processors/regexextract.go
- ingest/processors/regexextract_test.go
If your regexextract Template contains `${_SRC_}`, it will be replaced with a string representation of the SRC field of the entry. Thus you can now do something like this:
```
[Preprocessor "srcextract"]
Type=regexextract
Regex="msg: (?P<msg>.+)$"
Template=`{"srcip":"${_SRC_}", "msg":"${msg}"}`
```
and get entries which look like this:
```
{"srcip":"127.0.0.1", "msg":"foo bar baz"}
```
> Add special ${_SRC_} sigil to regexextract preprocessor.

- ingest/config/parse.go
This allows [::1], [::1]:4023, or ::1 as valid specifications.
> Fixes issue where Cleartext-Backend-Target=::1 would fail. 

- ingest/config/config.go
- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/main.go
- ingesters/KinesisIngester/config.go
- ingesters/KinesisIngester/main.go
- ingesters/MSGraphIngester/config.go
- ingesters/MSGraphIngester/main.go
- ingesters/O365Ingester/config.go
- ingesters/O365Ingester/main.go
- ingesters/SimpleRelay/config.go
- ingesters/SimpleRelay/json.go
- ingesters/SimpleRelay/lineHandlers.go
- ingesters/SimpleRelay/rfc5424Handlers.go
- ingesters/SimpleRelay/simple.go
- ingesters/kafka_consumer/config.go
- ingesters/version/version.go
- timegrinder/custom.go
- timegrinder/processors.go
- timegrinder/timeGrinder_test.go
adding the ability to specify custom time formats in config files for ingesters that use the timegrinder and a config.  Covers issue #83
> Issue 83 custom timestamp formats for ingesters

- go.sum
- ingesters/HttpIngester/auth.go
- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/gravwell_http_ingester.conf
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/main.go
Cleaning up some debug functionality, removing some fmt usage, and adding a new listener type that should be fully compatible with the Splunk HEC system.
This way applications that have been designed against HEC can just point at our ingester and "just work"
> Http fixup

- client/templates.go
- client/types/autoextract.go
- client/types/kits/types.go
- client/types/playbooks.go
- client/types/things.go
- kitctl/main.go
- kitctl/pack.go
Now breaks out far more fields when it unpacks. To properly deal with templates, we had to include the data type the GUI uses, so we can extract the query into its own file.
> Make kitctl way more intelligent

- client/types/render.go
- client/types/users.go
Removes SortRequired from types.RenderModuleInfo, as it is no longer used.
Adds the EntryCountValid field to types.BaseResponse so renderers can inform
clients whether or not the EntryCount number represents the actual number
of results which can be pulled back or not. (EntryCount gives the number
of entries which came *into* the renderer, but since some renderers do further
processing, it doesn't always indicate how many results are available).
Closes #227
> Remove deprecated SortRequired field and add EntryCountValid field.

- client/types/marshallers_test.go
- client/types/search.go
We don't want to send a "null" value, so this implements a little bit of logic to get around that.
> Implement custom marshaller for types.Element 

- client/types/kits.go
The first TODO comment is essentially handled by the call to `isLetterNumberPeriod` immediately preceding. As for validating macros, there's just not a lot you can do to validate macro IDs except checking if they're 0, given that we don't have a way to query the system for which macros actually exist.
> Remove outdated todos

- kitctl/main.go
kitctl import lets you bring in items and config macros from another kit file. This makes it easy to merge two kits, or to update a kit by just building a new kitfile containing the items you've updated in Gravwell.
> Add kitctl import and help commands

- ingest/entry_buff.go
- ingest/gravwell_log.go
- ingest/muxer.go
This is intended to make logging more straightforward in ingesters.
As it stands, logging works like this:
1. Create a logger
2. Call logging functions on logger until muxer is set up
3. Instantiate your muxer, passing it the logger
4. Call logging functions on muxer, which will also call the logger's functions
That's a bit incoherent. This change means we can do this:
1. Create a logger and start using it
2. Once we instantiate and start the muxer, add the muxer as a relay to the logger
3. Continue to call logger's log functions, which will also relay them through the muxer.
> Making IngestMuxer conform to the log.Relay interface

- ingest/gravwell_log.go
- ingest/muxer.go
- ingesters/GooglePubSubIngester/main.go
- ingesters/HttpIngester/main.go
- ingesters/IPMIIngester/main.go
- ingesters/KinesisIngester/main.go
- ingesters/MSGraphIngester/main.go
- ingesters/O365Ingester/main.go
- ingesters/PacketFleet/main.go
- ingesters/SimpleRelay/json.go
- ingesters/SimpleRelay/main.go
- ingesters/SimpleRelay/simple.go
- ingesters/collectd/main.go
- ingesters/fileFollow/main_linux.go
- ingesters/kafka_consumer/main.go
- ingesters/netflow/handlers.go
- ingesters/netflow/main.go
- ingesters/networkLog/main.go
- ingesters/sqsIngester/main.go
Instead of having a bunch of logic for the ingest muxer to send logs to the
gravwell tag, instead just provide convenience functions which write to
the Logger which was passed in the config. In turn, that logger can set
the ingest muxer as a *relay*, which writes the log messages to the gravwell
tag. This has the side effect of getting *all* log messages into the gravwell
tag, provided you don't fill up the (generous) buffer before finally connecting
to an indexer.
Note: This is not yet ready, the rest of the ingesters need to be walked to deal with things properly. networkLog and SimpleRelay demonstrate what needs doing, though.
> WIP: Rework how ingesters log.

- client/types/scheduledsearch.go
As we want to add more and more information about the execution of a flow, it makes sense to consolidate everything into a single struct per node of the flow
> Change DebugPayloads and LastLogs into a single FlowResults map

- client/types/scheduledsearch.go
This indicates which node, if any, failed to parse
> Add ErrorNode field to FlowParseResponse

- ingest/processors/srcrouter.go
- ingesters/fileFollow/main_linux.go
- ingesters/fileFollow/processing_windows.go
closes issue #343
ingest muxer will fixup nil SRC values, so don't bomb if we can't get it during startup.
> addressing issue #343, its ok if the src is nil, so just pass it in

- client/searchCtrl.go
- client/types/render.go
request so that you can ask for unmutated entries from renderers like text, hex, and pcap.
This will have no affect on the raw renderer or general usage, but allows for getting un mutated entries from text, hex, and pcap.
> updating raw results

- ingesters/SimpleRelay/.gitignore
- ingesters/SimpleRelay/config.go
- ingesters/SimpleRelay/main.go
- ingesters/SimpleRelay/regexConfig.go
- ingesters/SimpleRelay/regexHandlers.go
- ingesters/SimpleRelay/regex_test.go
A RegexListener specifies a regular expression which marks the split between entries.
The regular expression can contain "prefix" and "suffix" capture groups which will be
kept with the appropriate entry, thus given the following regex:
Regex=`(?P<suffix>END)|(?P<prefix>\d{4}-\d{1,2}-\d{1,2})`
and the following data input:
2022-03-30 message 1 END|2022-04-01 message 2 END
you will get two entries:
2022-03-30 message 1 END
2022-04-01 message 2 END
> Add RegexListener to SimpleRelay ingester.

- client/client.go
- client/info.go
- client/ingest.go
- client/types/api.go
- client/urls.go
IngestEntries previously used /api/ingest/json, which has a 24MB
default limit.  This means you could only ingest 24MB of entries at
a time or else you'd get an error from the webserver. This change
instead uses the reimport API, which can also handle search entries,
but does it via a streaming multipart request and goes around the
size limits.
Also adds a function to fetch the GUI Settings object.
> Use the reingest API for IngestEntries

- client/client.go
- client/templates.go
update error constant on client and change the templates API to get the entire wireTemplate back
> small fmt on client error and change to Template API

- ingesters/GooglePubSubIngester/config.go
- ingesters/GooglePubSubIngester/main.go
- ingesters/GooglePubSubIngester/pubsub_ingest.conf
This updates the Google pubsub ingester so that it doesn't needs as aggressive privs.  It now walks a series of operations trying to get a handle on a subscription that require the least privs.
For example, if the subscription config is set, then it will try to use that, if it can't get what it needs it fails.
If it is NOT set then it tries to test it and create it (requiring more privs).  Using this escalating procedure its possible to configure a security token that doesn't really let the ingester do THAT much.
But if you DO give it a ton of privs it will set stuff up itself.
> Update google pubsub to limit needed privs

- ingest/log/logging.go
Calling FatalCode was messing up the call depth. It is not a complex bit of
code, so instead we just duplicate the logic into Fatal.
> Fixes #420: Fatal log call depth.

- client/types/scheduledsearch.go
- client/urls.go
- client/userfiles.go
UserMailResponse is what the server sends back after a successful email submission.
GetUserFileDetails lets you get information about a single file, rather than fetching the contents.
> Add UserMailResponse struct and GetUserFileDetails function.

- client/urls.go
- client/userfiles.go
We decided to change the endpoints around:
`/api/files/<id>` now fetches metadata about the file instead of the contents.
`/api/files/<id>/raw` now fetches the contents of the file.
This pattern matches the one used for resources.
> Change the URLs used for GetUserFile and GetUserFileDetails

- client/admin.go
The extraction creation API now returns the full object instead of just an ID.
We also added an endpoint to fetch a single AX.
> Update AddExtractions, implement GetExtraction

- go.mod
- go.sum
- ingest/log/logging.go
- ingesters/winevents/main.go
- ingesters/winevents/processing.go
working on converting winevent over to the standard logging structure
Had to add a new relay type on the `ingest/log` package.
closes https://github.com/gravwell/gravwell/issues/428
> standardizing winevent internal logs

- client/types/search.go
The WordOffsets array contains [2]int arrays, each specifying the
absolute offsets of a word within the DATA field of the associated
entry. This can be used to provide clickable filters in the UI.
> Add WordOffsets field to ExploreResult struct.

- migrate/config.go
- migrate/main.go
fixing typo in config type that was referencing the wrong config object and removing linux build constraints.
This should work just fine in windows
> migrate fixes

- client/types/license.go
Just add another structure so that we can handle mixed license usage
> adding a meta structure for license usage reporting

- client/routingSockets.go
- client/searchCtrl.go
If you open a search and then don't interact with it for a long time, the websockets will be closed by the webserver.
If you want to do this, call Ping() periodically.
> Add the Ping() function on the Search type

- ingest/processors/corelight.go
- ingest/processors/processors.go
This is the first draft. It hard-codes JSON->TSV conversions for the following types:
* conn
* dhcp
* dns
* files
* http
* ssl
* weird
* x509
* ssh
* sip
* dpd
* snmp
* smtp
* pe
* tunnel
* socks
* software
* syslog
* rfb
* radius
* rdp
* ftp
* intel
* irc
* kerberos
* mysql
* modbus
* notice
* signature
* smb_mapping
* smb_files
There are no provisions for ignoring certain log types.
This PR addresses [ISSUE_LINK]
> Add corelight JSON->TSV processor

- ingest/processors/corelight.go
- ingest/processors/corelight_data_test.go
- ingest/processors/corelight_test.go
- ingest/processors/processors.go
Basically because of the "clean" phase of the map fixup we introduce some ambiguity and failures.
I think we need to remove the clean phase and just specify the headers in the exact form that corelight throws them, we don't emit the headers anywhere, so its OK to keep them as is.
Test included.
example logs here: https://docs.zeek.org/en/master/logs/index.html
> this has some tests that show issues with how we do this conversion

- ingest/processors/corelight.go
- ingest/processors/corelight_data_test.go
- ingest/processors/corelight_test.go
Also:
* Extract timestamps with timegrinder, just in case we have different time stamp formats from different systems
* Fix broken ftp tests
> Fix corelight conn log formatting.

- client/client.go
Previously, we told users to call Login, then call Sync, which fetches information about the user. This tends to be a bit fraught in practice, because users reasonably assume that after calling NewClient and Login, you should be able to use the client -- but some calls *will* fail, because the client doesn't know the user's UID. This change just calls syncNoLock as the last step of Login.
Closes #474
> client: Do a sync in the Login function.

- client/admin.go
- client/kit.go
- client/library.go
- client/pivots.go
- client/playbooks.go
- client/resources.go
- client/templates.go
- client/userfiles.go
We decided in #473 that that client shouldn't be attempting to validate whether or not the user is an admin--the webserver will handle it! This strips out checks everywhere I could find them.
Closes #473.
> client: don't check if user is admin or not

- ingesters/netflow/netflow_capture.conf
Port 6343 is more commonly used for s-flow, and it confuses some appliances to try and send ipfix there.
> Change default ipfix listener port.

- ingest/api.go
- ingest/muxer.go
Per #555, we now ship the hostname when we report ingest state.
> ingesters: add hostname to the ingest state object

- client/types/kits/types.go
packed kit resources didn't bring along labels.
> add missing labels to packed kit resources

- client/secrets.go
- client/urls.go
This endpoint is only accessible if you've done the full searchagent auth dance. This is how the searchagent will be able to fetch e.g. SSH keys from the secret store for use in automations. Regular users cannot touch this API.
> Implement the GetFullSecret API call.

- ingesters/massFile/processing.go
Brought up in security review, not exploitable but it flags some automated tools so might as well clean it up and fix.
> addressing path clean concerns from security review

- ingesters/SimpleRelay/json.go
- ingesters/SimpleRelay/jsonConfig.go
JSONListener no longer HAS to have extractors
we now read json objects proper, this means pretty printed as well
This PR addresses https://github.com/gravwell/gravwell/issues/602
> JSON Listeners can eat real JSON objects

- client/types/render.go
to also throw up the list if ingesters that an indexer has seen but hasn't seen lately
This is so we can inform the API about ingesters we saw before but aren't currently connected
> adding new member to ingester stats

- filewatch/filewatch_test.go
- filewatch/followers.go
- filewatch/followers_test.go
- filewatch/handler.go
- filewatch/reader.go
- ingest/entry/enumerated_test.go
- ingest/entry/enumerated_types.go
- ingesters/fileFollow/config.go
- ingesters/fileFollow/main_linux.go
- ingesters/fileFollow/processing_windows.go
This adds the ability to attach a file name to entries as they are consumed in file follower.
> Add Attach-Filename directive to file follower

- go.mod
- go.sum
- ingesters/snmp/.gitignore
- ingesters/snmp/config.go
- ingesters/snmp/main.go
- ingesters/snmp/snmp.conf
Per #564, implements an ingester which can accept SNMP Trap messages and ingests them as JSON. Supports SNMP versions 2c and 3.
For SNMPv3, supports MD5 and SHA auth protocols and DES privacy protocol. Messages with mis-matching auth/privacy settings will be dropped.
> Add basic SNMP ingester

- go.mod
- go.sum
- winevent/wineventlog/README
- winevent/wineventlog/utils.go
- winevent/wineventlog/wineventlog_windows.go
This PR works on https://github.com/gravwell/gravwell/issues/582
I still can't replicate the behavior of that issue but I CAN see how if windows was letting NULLs slip into the XML formatting then the hand rolled implementation of UTF16->UTF8 would stop decoding. 
Its a shot in the dark, but also that hand rolled implementation is scary compared to `/x/text` libraries.
> try to knock down some code paths that MIGHT cause #582

- timegrinder/custom.go
- timegrinder/processors_extra.go
- timegrinder/timeGrinder_test.go
If it is January 30, and we read a syslog message that starts "Oct 5 13:00:00", the vast majority of the time that's coming from the *previous* year, not from 9 months into the *future*.
This change does the following for the Syslog timestamp format and for Custom formats which do not include the year:
* If setting the year of the timestamp to the current year places it more than 25 hours into the future, we instead set it to *last* year.
* If setting the year of the timestamp to the current year places it in the immediate future (<25 hours ahead), we use the current year, assuming clock drift or timezone issues.
* If using the current year places the timestamp in the past, we use the current year.
> Make timegrinder smarter in guessing the year.

- ingesters/SimpleRelay/json.go
- ingesters/SimpleRelay/regexHandlers.go
- ingesters/SimpleRelay/regex_test.go
Updates the regexListener in simple relay so that we can do UDP, TCP, TLS.  UDP was missing.
I had to change some form and function a bit for regex loop so that i didn't have to duplicate a bunch of code for UDP.
This should remove some needless async too though, so maybe resource reduction.
This PR addresses https://github.com/gravwell/gravwell/issues/623
> fixing regex handler so that it can do TCP, UDP, or TLS

- ingesters/snmp/main.go
This gives people a little more flexibility. You can set the  `Community` to require a community string on traps, or leave it blank to accept everything.
> if Community is unset, accept traps from any community

- ingesters/HttpIngester/gravwell_http_ingester.conf
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/hec_config.go
- ingesters/HttpIngester/kinesisdeliverystream.go
- ingesters/HttpIngester/main.go
Change the URL parameter for HEC-Compatible-Listener to be the base (`/services/collector`) instead of the "event" path (`/services/collector/event`). This may be a breaking change for some setups, but I think we can make the following assumptions:
1. Most deployments with the HEC listener are using the default
2. Even if someone specified `URL=/services/collector/event`, it will still work ok because we'll listen on that endpoint with the same handler as on `/services/collector/event/event`. ACKs won't be quite right, but ACKs weren't quite right anyway.
The raw endpoint now splits on lines. You can specify a different line break string via e.g. `Raw-Line-Breaker=";"`
If an ACK is requested (by specifying a channel in the request) we will always send an ACK ID.
Also improves logging to …
> Improve the HEC listener.

- ingesters/HttpIngester/hec_config.go
We previously expected you to say `URL=/services/collector/event` and then we needed to get `/services/collector` from that to figure out other paths. Now we expect you to say `URL=/services/connector` and we build from that, but I forgot to change this line.
> HTTP/HEC: we changed how URL works, so we need to treat it differently

- ingesters/base/base.go
current method required default config dirs and also prevented running "-h" or "-version" without good configs.
> Adjusting ingester base config parsing to be less strict and allow `-h` with broken fields

- client/types/abac.go
I found a couple of spots where the API should respond with an empty array but sends a `null` instead. This PR proposes initializing a couple of empty slices to address that inconsistency.
> Fix a couple of "nil vs []" things

- client/types/searchentry.go
- generators/gravwellGenerator/regex.ax
- ingest/entry/entry.go
- ingest/entry/enumeratedblock.go
- ingest/processors/corelight_test.go
- ingest/processors/jsonsplit.go
- ingest/processors/jsonsplit_test.go
- ingest/processors/plugin_test.go
- ingest/processors/processors_test.go
- ingest/processors/srcrouter_test.go
- ingest/processors/vpc.go
- ingest/processors/vpc_test.go
This PR does the folllowing:
1. Adds a method on entry.Entry to copy enumerated values from one to another
2. Adds a method on entry.Entry to retrieve enumerated values
3. Updates the preprocessors that create wholly new entries (splitters, etc...) to preserve EVs from the original
4. Adds tests to ensure we don't have regressions
This PR addresses https://github.com/gravwell/backend/pull/584
> Fixing up preprocessors to maintain EVs

- ingesters/HttpIngester/gravwell_http_ingester.conf
example in config was wrong.
Kinesis delivery stream is unsupported, but the config snippets should still be right.
> fix the kinesis ingester config example

- client/types/abac.go
- client/types/search.go
- ingesters/version/version.go
Updating the types used for launching and attaching to searches.
These types exclude the error members and other garbage because REST doesn't need that.
Also merging dev:
dev -> Preview/search-store plus
> reforming start and attach types

- client/types/abac.go
Javascript really does not like to get a null when it expects an empty array, but that's what Go will send if your struct contains e.g. a []string and you don't explicitly initialize the slice. These custom marshallers make sure we send an empty array, making the frontend's life easier.
Go desperately needs some way to tell the JSON encoder that we want this behavior, see:
https://github.com/golang/go/issues/37711
https://github.com/golang/go/issues/27589
https://github.com/golang/go/pull/27813
> Add custom marshallers for some ABAC types.

- filewatch/filewatch.go
- filewatch/followers.go
- filewatch/liner_linux.go
- filewatch/liner_windows.go
- filewatch/reader.go
- filewatch/reader_windows.go
- filewatch/regex.go
so that if its been long enough and we don't have a trailing delimiter, we just consume the last entry.  This to deal with files that don't write a trailing newline
This PR addresses https://github.com/gravwell/gravwell/issues/668
> fixing up the file follower 

- osv-scanner.toml
We don't use the S3 library in the way the vuln describes and don't want/need write permissions for S3 buckets.   We also don't support KMS in the ingester, so basically its not possible to trigger the Amazon library vulnerability using our ingester.
> adding OSV TOML to announce invalid vuln reports

- ingest/log/stderrlog_unix.go
- ingest/processors/persistent_buffer.go
- ingest/processors/processors_darwin.go
We don't actually use close on exec in Dup3, so Dup2 is fine, which macOS requires. The only other fix is a build constraint.
> make the ingest library build on macos, with or without m1

- client/searchCtrl.go
SearchURL returns a URL that should be valid to access the search results.
SearchStatus fetches the SearchCtrlStatus for a single query.
> Add SearchURl and SearchStatus functions to the client library

- client/searchCtrl.go
- client/types/api.go
This allows the webserver to give its "canonical" address, the one it thinks users should be coming in through.
Also updates the SearchURL function to use that address if available.
> Add ExternalAddr to GUISettings object

- filewatch/handler.go
- ingesters/utils/ignore_test.go
- ingesters/utils/lineignorer.go
- ingesters/utils/readers.go
- migrate/files.go
Addresses #707.
Moved the LineIgnorer definition from filewatch to utils so we could apply it here.
> Add Attach-Filename and Ignore-Glob to the migrate ingester

- ingest/config/setingesteruuid_windows.go
the API on unix didn't translate exactly to windows, so we needed to rework the paths into their parts before calling os.Mktemp.
> fixing windows implementation of the setIngesterUUID function

- client/types/kits.go
- client/types/kits/types.go
Also adds InstallationGroups field to the KitConfig struct
> get rid of the GID field for kits, use GIDs instead

- ingest/attach/attach.go
- ingest/attach/attach_test.go
- ingest/entry/entry.go
- ingest/entry/enumeratedblock.go
- ingest/entry/enumeratedblock_test.go
- ingest/muxer.go
- ingesters/SimpleRelay/config.go
- ingesters/SimpleRelay/config_test.go
- ingesters/SimpleRelay/jsonConfig.go
- ingesters/SimpleRelay/main.go
- ingesters/SimpleRelay/regexConfig.go
- ingesters/base/base.go
- ingesters/s3Ingester/config.go
- ingesters/snmp/config.go
This implements the "attach" thing so that any ingester can slap a global config and the ingester will attach stuff.
It allows for attaching arbitrary strings as well as some keywords:
Here is an example config for Simple Relay:
```
Log-Level=INFO
Log-File=/opt/gravwell/log/simple_relay.log
[Attach]
host="$HOSTNAME"
foobar="foo to the bar"
ingested="$NOW"
ingester="$UUID"
#basic default logger, all entries will go to the default tag
#no Tag-Name means use the default tag
[Listener "default"]
Bind-String="0.0.0.0:7777" #we are binding to all interfaces, with TCP implied
Tag-Name=default4
```
This will attach the ingester UUID, timestamp at point of ingestion, and the derived hostname.  It also attaches arbitrary string `foo to the bar`
> EV attach in ingesters

- ingesters/IPMIIngester/config.go
- ingesters/IPMIIngester/main.go
- ingesters/PacketFleet/config.go
- ingesters/PacketFleet/main.go
- ingesters/SimpleRelay/main.go
- ingesters/networkLog/config.go
- ingesters/networkLog/main.go
- ingesters/sqsIngester/config.go
- ingesters/sqsIngester/main.go
This makes it easier to include attach stuff and any future changes to ingest muxer stuff
The following ingesters are converted in this PR:
- sqs
- packetfleet
- networklog
- ipmi
> Converting the main boiler plate code over to base

- client/flows.go
- client/types/alert.go
- client/types/scheduledsearch.go
FlowParseRequest and ScheduledSearch types now have a DebugEvent type. If set, it will be injected into the incoming payloads of flows in the following cases:
- When parsing a flow via FlowParseRequest
- When running a flow in debug mode (DebugMode = true)
Also introduces the ParseReactiveFlow function on the client, to make it easier to validate flows as they are being built.
> Add DebugEvent fields for flows.

- client/types/kits.go
- client/types/kits/types.go
InstallationVersion records the Gravwell version at the time of kit installation/update.
GUID in PackedScheduledSearch helps with the upgrade process.
> Add InstallationVersion to KitState, GUID to PackedScheduledSearch

- client/types/kits/types.go
Brings it in line with convention elsewhere
> change GUID to UUID in packedscheduledsearch JSONMetadata

- client/flows.go
- client/scheduledSearch.go
- client/urls.go
You can fetch a flow or scheduled search by GUID or by ID. This change enables that in the client library.
> Make GetFlow and GetScheduledSearch more flexible.

- client/types/alert.go
This lets the user specify how many events should be allowed per triggering of the alert. If zero, the search agent will use a default.
Also cleans up a bunch of omitempty tags that we're no longer using.
> Add MaxEvents field to AlertDefinition type.

- client/alerts.go
they should not be using the int32 IDs
This PR addresses [ISSUE_LINK]
> change alert validation functions to take UUIDs.

- ingesters/winevents/config.go
- ingesters/winevents/processing.go
> fixing config block structure that is thrown in the windows event ingester

- ingest/log/logging.go
- ingest/log/logging_test.go
- ingest/log/stderrlog_unix.go
- ingest/log/stderrlog_windows.go
- ingesters/winevents/main.go
This fixes the ingesters so that logs that go to stderr do NOT contain the RFC5424 error message, just the message and values.
Here is what happens now.
If you DO NOT redirect stderr:
1. logs come out to stderr as RFC5424
2. only error, critical, and fatal are emitted to stderr
If you DO redirect stderr:
1. logs going to the redirected stderr file are emitted as RFC5424
2. logs going to actual stderr (the journal) are emitted as raw with no timestamp (so the journal can handle it)
3. only error, critical, and fatal are emitted to stderr
This PR addresses #902 
This PR addresses #901
> fix ingester stderr logger

- filewatch/filewatch.go
- filewatch/filters.go
- filewatch/followers.go
If a writer is writing really fast, we can sometimes get "stuck" chasing the tail of a given file during the initial sync. This change notes the size of the file when we begin the process and doesn't read past that size, even if the file has been written since then.
> Improve handling of filefollow pre-process

- client/types/things.go
Other types do it, and it makes sense to pack it. Also, don't set t.Updated to the current time when generating the Thing() from a Wire* object.
> Add Updated fields to WireUserFile and WireSearchLibrary

- client/types/render.go
This makes it simpler for UIs to tell the user how much data is coming in per indexer (or over the whole cluster).
> Add EntriesPerSecond and BytesPerSecond to IngestStats.

- client/client.go
Some APIs cache heavily, this allows for busting those caches when needed.
> adding ability to set no-cache headers on all Gravwell requests

- ingesters/HttpIngester/gravwell_http_ingester.conf
- ingesters/HttpIngester/main.go
- ingesters/networkLog/network_capture.conf
- migrate/splunkconn.go
Force TLS 1.2 or better for all servers, simple relay already did this, but now HTTP ingester does too
Also clean up some TLS related configs and bad settings.
This PR addresses https://github.com/gravwell/gravwell/issues/942
> Clean up some TLS min versions and default configs

- timegrinder/timeGrinder_test.go
We have a couple of formats that do not contain years, so there is some wonky logic to try and figure out what the appropriate year is.
For example, if we only see the date Jan 10, then we need to figure out WHICH Jan 10.  So we basically add the current year and check if its too far in the future (to account for clock drift and timezone garbage).  If it is, then we take the previous year.  It is not great, but it generally handles the crappy time format.
> fix bad test on timegrinder that will always fail from Jan 1 to Jan 8 every year

- generators/gravwellGenerator/jsongen.go
- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/hec_config.go
- ingesters/SimpleRelay/rfc5424Handlers.go
- ingesters/SimpleRelay/rfc6587Handlers.go
- ingesters/massFile/processing.go
- ingesters/multiFile/main.go
- ingesters/regexFile/main.go
- ingesters/s3Ingester/utils.go
- ingesters/utils/readers.go
There were a few ingesters that were not Cloning the response of calls to a `bufio.Scanner.Bytes()` call.  It is extremely difficult to manifest the behavior on any ingester but the HTTP ingester due to the raciness of getting data into the ingest muxer. 
This fixes usage across all ingesters and also cleans up some kind of sloppy append() clone falls.
Addresses https://github.com/gravwell/gravwell/issues/949
Oops, this also includes the following:
1. tweak to megajson generator to simulate timestamps that suck (deeply embedded unix timestamp)
2. tweak to URL-Parameter-Attach to support a wildcard which means attach everything you see (but tag)
3. fix HEC compatible listener so that it supports custom timestamp formats (for /raw endpoint)
> fix unsafe usage of scanner Bytes() method

- client/types/render.go
This adds in 4 new members to the IngestStats structure so that we can report a running "tail" of ingest on the stats pages.
> adding ingest stats tail members

- ingesters/HttpIngester/hec.go
- ingesters/HttpIngester/hec_config.go
This allows definitions like so:
```
[HEC-Compatible-Listener "testing"]
URL="/services/collector" #If URL is omitted, the default is set to /services/collector
TokenValue="test" #set the access control token
Tag-Name=hec
Debug-Posts=true
Routed-Token-Value=`test2:hec2`
Routed-Token-Value=`"this is a complex token":hecX`
Tag-Match=`"foobar":hec99`
Tag-Match=`foobar2:"hec88"`
[HEC-Compatible-Listener "testing2"]
URL="/services/collector2" #If URL is omitted, the default is set to /services/collector
TokenValue="test" #set the access control token
Tag-Name=hec2
```
Basically enabling routes for tags to be controlled by `sourcetype` overrides OR tokens.  This is required because many external services that expect to talk to HEC do not know how to throw at alternate URLs.  They ONLY know …
> adding token based routing on HEC compatible listeners

- ingest/config/validate/validate.go
- ingesters/Shodan/main.go
- ingesters/base/base.go
- ingesters/canbus/main.go
- ingesters/fileFollow/main_windows.go
- ingesters/winevents/main.go
- migrate/main.go
Validate config function was too strict and trying to assert that everything was an ingester, this broke validate on other components.
> tweak the validate function a bit so it can be used by internal components too

- generators/base/base.go
- generators/gravwellGenerator/main.go
This allows the generator to be used to test tag negotiation and connections without sending entries
> tweaking some configs to allow generator to be used to just test

- ingesters/fileFollow/processing_windows.go
- ingesters/fileFollow/product.wxs
provide a default on our windows file follower config and don't let the service fail too fast when installing
> fixup automated installs on windows file follower

- ingesters/HttpIngester/hec.go
- ingesters/fileFollow/product.wxs
- ingesters/winevents/product.wxs
The other issue is a customer HEC ingester was throwing a completely bonkers timetamp in a way that totally violates what is supposed to be happening.
So this deals with that edge case.... :(
> Fix HEC ingester timestamp processing and Windows Upgrade with point versions

- client/types/things.go
It makes Javascript clients unhappy; if we fix it here, we should get improvements for free in a lot of our APIs.
> Try to avoid sending a nil WriteAccess.GIDs field for Things.

- ingesters/collectd/routines.go
don't return an error if we are leaving a routine due to a context.Cancel
> make collect ingester not bark every time you restart it

- generators/base/base.go
Run the generator like this:
```
./gravwellGenerator \
-clear-conns=172.17.0.3 \
-tag-name=default \
-type=syslog \
-duration=10d \
-entry-count=100000000 \
-status \
-time-is-an-illusion
```
Get this:
```
/opt/gravwell/storage/default # du -sh ./*/*.index
1020.0K	./76eba/76eba.index
540.0K	./76ebb/76ebb.index
420.0K	./76ebc/76ebc.index
396.0K	./76ebd/76ebd.index
396.0K	./76ebe/76ebe.index
396.0K	./76ebf/76ebf.index
396.0K	./76ec0/76ec0.index
126.8M	./76ec1/76ec1.index
185.7M	./76ec2/76ec2.index
184.3M	./76ec3/76ec3.index
156.1M	./76ec4/76ec4.index
156.2M	./76ec5/76ec5.index
156.2M	./76ec6/76ec6.index
141.7M	./76ec7/76ec7.index
/opt/gravwell/storage/default # 
```
Then feel the pain.
> add flag to make generator produce bonkers timestamp distributions

- generators/base/base.go
It was respecting duration, when it should not have been.
> fix timestamp generation on the generators when in stream mode

- client/alerts.go
- client/types/alert.go
Also brings in a little function we can use to resolve, in the context of a particular user, exactly which scheduled search/script/flow is being referenced by a GUID.
> Add functions to get alerts which use a specific consumer/dispatcher

- chancacher/chancacher_test.go
- ingest/entry/entry.go
- ingest/entry/entry_test.go
- ingest/entry/enumeratedblock.go
- ingest/muxer.go
GobEncode method had a pointer receiver, this silently fails.
> Fix entry GOB encoding

- chancacher/chancacher_test.go
- ingest/entry/entry.go
These things shouldn't be re-used and it only causes opportunities for bugs by upstream users.
> do not re-use underlying slices

- chancacher/chancacher_test.go
- ingest/entry/entry.go
- ingest/entry/entry_test.go
- ingest/entry/enumerated.go
- ingest/entry/enumeratedblock.go
- ingest/muxer.go
cherry picking in:
6d68f41b5debeaeb4a1f34cde767485ec3b5afbf
913ea5ec64e416ac8926b509c289895e4844b365
177d0bdd582d03d739020ae58324a722e714f4c9
3e30dc0fdf25798e0f904e5e49115373a3e8b809
597018dad84a55d5496177bd7cdbfcf9debbdca4
> cherry pick dev changes around EVs and gob into master

- ingesters/HttpIngester/gravwell_http_ingester.service
- ingesters/networkLog/gravwell_network_capture.service
These aren't used and systemd now barks about it.
> remove PIDFile specifications from service files

- client/urls.go
We decided to put it under /api/login instead
> change url for mfa login

- ingest/muxer.go
This PR addresses no specific issue and is for readability and performance only.
> bring in ingesterstate tweaks to control how and when config blocks are thrown

- ingest/entryReader.go
- ingest/entryWriter.go
current close deadline is 10s, this seems like a LOOONG time to close out connections and should never hit; but it does act like a nice safety net to avoid leaks on truly stalled connections.
> set deadline on close so we don't stall on close during shutdown

- client/types/render.go
so renderers can provide warnings about over limits and storage when finishing
> adding Warning member on stats and base response_

- .github/workflows/sync-branches.yml
The latest release of [sync-branches](https://github.com/gravwell/sync-branches) lets the user provide labels to automatically apply/remove whenever a conflict is detected on a sync PR.
This PR proposes...
- refactoring the sync-branches **workflow** to a matrix, because it's less repetitious
- supplying labels for the sync-branches **action** to use when it detects conflicts
> ci: Supply conflict labels to sync-branches

- client/notifications.go
- client/utils.go
we didn't have an admin method to get all notifications and we were wrapping the notifications URL very stupidly.
> fixing up usage of notifications APIs

- client/types/search.go
This allows us to pass along information about why a query failed.
> Add Error fields to SearchInfo and SearchCtrlStatus

- filewatch/filewatch.go
- filewatch/filters.go
- filewatch/followers.go
- filewatch/fwork_windows.go
- ingesters/fileFollow/processing_windows.go
This fixes two main bugs:
1. The file follower could exit on error if a file is rotated out during the Catchup call.  This seems like one hell of a race to hit, but I am able to trigger it on the regular with Windows.  Never could in Linux.
2. Windows file follower calls its equivelent of a "stat" with SHARE attributes, because apparently "stat" in windows grabs a file handle in an exclusive way and holds it for a long time... because reasons.
> File follower and windows file lock fun

- .github/workflows/golang-testing.yml
We're currently limiting test jobs to PRs that target certain branches. We **should** be running tests on **all** PRs that are opened. That is, we should never merge code that hasn't had tests run and pass.
This PR proposes 
- removing the branch inclusion list, so that all PRs will have tests run on them
- whitespace cleanup
> ci: Run tests on any PR

- client/types/render.go
- client/types/searchentry.go
- client/types/text.go
Updates gravwell/backend-issues#5692
> Conditionally encode entry data with base64 instead of always.

- client/ingest.go
We were intentionally removing EVs on IngestEntries, no idea why, these are used all over, they should be kept.
This PR addresses https://github.com/gravwell/gravwell/issues/1278
> fix client to no wipe out enumerated values on ingest, covers issue #1278

- client/types/host.go
This PR proposes adding `AIRemoteProcessor` as a field on `DeploymentInfo`.
> Add AIRemoteProcessor field

- ingest/entry/defaults.go
- ingest/entry/enumeratedblock.go
- ingest/entry/enumeratedblock_test.go
- ingest/ingestConnection.go
- ingest/muxer.go
- ingest/simple.go
This PR adds some controls in negotiating tags at the ingest layer so that ingesters can fail faster when when trying to negotiate too many tags.
Before the remote side is tracking and will reject too many tags, but that can cause buffering and connection bumps.  This will make it so if a plugin or ingester goes haywire the ingest muxer can shut it down before it has to do the whole loop and have a remote federator/indexer reject the tag allocation.
Just a fail faster patch.
> Tag rollover control

- generators/gravwellGenerator/consts.go
- generators/gravwellGenerator/main.go
before it was generating basically infinte orthogonality, this caps things to some reasonable constant.
> make the generator less crazy on very high throughput generator calls

- client/types/cbac.go
- ingest/muxer.go
- ingest/utils.go
- ingest/utils_test.go
This PR does a few things:
1. Dynamic Tag negotiation will only actually occur on an ingestConnect if an entry actually shows up
2. dynamic tag negotiation won't block and wait for each ingestConnection to do its thing
> making tag negotiation async and triggered by actual usage

- ingest/muxer.go
its pretty easy to drop data if you don't Sync the ingest muxer before closing, all our ingesters always do a sync then close but other users may not.
If you DO do a proper sync then close then this call adds 10ms to the close call, but thats fine, we stripped out a 500ms delay earlier.
> sync before we close

- ingest/entryWriter.go
- ingest/ingestConnection.go
- ingest/muxer.go
- ingest/simple.go
- ingest/utils.go
This PR does teh following:
1. Removes the global muxer level ingester state reporting routine
2. Adds some functionality in the individual muxer routines to have individual ingestConnections report state
3. Reduces the frequency of ingester state updates when the only thing changing is ingest rates
4. Adds some timeouts to the ingestConnection close routines so that we can detect and close bad connections
5. Adds a new notification boolean on the ingestConnection routine that can signal to the system that grabs new connections that we think the upstream host is unhealthy and we should backoff and sleep before grabbing a new connection
> muxer and ingest reporting resilience

- chancacher/chancacher.go
- ingest/entryConfBuffer.go
- ingest/entryWriter.go
- ingest/ingestConnection.go
- ingest/muxer.go
This PR is more work on cleaning up abnormal shutdown and entry recovery in the case of errors.
It does the following:
1. When committing/closing the cache we also release the lock on the file (bug)
2. When grabbing outstanding entries on shutdown or failure we also purge the entryConfBuffer
3. Added a new ejectOutstandingEntries() call to ingestConnections and buffers and stuff
> add release of file lock for cache

- ingest/entryWriter.go
- ingesters/HttpIngester/main.go
- ingesters/IPMIIngester/main.go
- ingesters/PacketFleet/main.go
- ingesters/SimpleRelay/main.go
- ingesters/collectd/main.go
- ingesters/diskmonitor/main.go
- ingesters/fileFollow/main_unix.go
- ingesters/fileFollow/processing_windows.go
- ingesters/kafka_consumer/main.go
- ingesters/massFile/main.go
- ingesters/netflow/main.go
- ingesters/networkLog/main.go
- ingesters/pcapFileIngester/main.go
- ingesters/reddit_ingester/ingest.go
- ingesters/s3Ingester/main.go
- ingesters/session/main.go
- ingesters/snmp/main.go
- ingesters/sqsIngester/main.go
- ingesters/utils/runtime.go
> Crank up the exit sync on production ingesters now that the timeout is more strictly respected

- ingest/config/env.go
- ingesters/HttpIngester/config.go
- ingesters/HttpIngester/handlers.go
- ingesters/HttpIngester/main.go
What it does do:
1. specify a default number of maximum active connections to the HTTP ingester
2. specify a default number of maximum concurrent requests
3. move the health check API up the stack to respond faster with less standup
> HTTP ingester more defense mechanisms

- .github/workflows/golang-testing.yml
- go.mod
- go.sum
- ingesters/SimpleRelay/rfc5424Handlers.go
adding ability to force out data on an RFC5424 or RFC3164 stream that doesn't have a follow up header block
This PR addresses no specific issue, but tries to make SimpleRelay detect stale data on a TCP connection that doesn't have a follow up RFC header block.
Might be worth porting into the other RFC reader type and maybe regex reader types too.
I did some limited speed tests using the generator on my workstation and saw no difference whatsoever in syslog throughput.
> SimpleRelay add stale data flush on RFC TCP streams

- client/types/encoding_test.go
- client/types/manage.go
encoding/json won't handle years greater than 9999, so define a max timestamp and set the ShardInfo's Start/End fields to that in MarshalJSON if they're too big.
> Add special cases to catch ShardInfo too far in the future.

- generators/gravwellGenerator/main.go
- ingest/muxer.go
In the ingest muxer Sync code if a zero value is provided (no timeout) we were not respecting that zero value timeout all the way through all the synchronization mechanisms, so it could often cause instant timeouts rather than No timeout.
> fix up sync timeouts on ingest muxer when a zero value timeout is provided

- ingesters/HttpIngester/hec.go
This PR addresses no specific issue, but the HEC health API was not calling WillBlock (which checks cache levels and all that) and was instead just returning based on whether we had upstream ingest connections.
> make HEC health API call WillBlock instead of trying to figure out health by hand

- ingesters/winevents/main.go
- winevent/wineventlog/zsyscall_windows.go
Fix bad syscall conversions from the deprecated API to the new syscallN interface
> fix some dumb inverted logic and do the syscallN dance correctly

- gwcli/mother/builtins.go
- gwcli/mother/mother.go
- gwcli/stylesheet/styles.go
- gwcli/tree/queries/attach/actor.go
- gwcli/tree/queries/attach/attach.go
- gwcli/tree/queries/attach/selecting.go
- gwcli/tree/queries/attach/shared.go
This PR addresses https://github.com/gravwell/gravwell/issues/1138.
This PR is focused on upgrading `attach` after the initial implementation.
The primary two changes are:
1.  Creation of a details view and its composition with the list. the details view is a couple panels containing additional information about the currently selected item in the list. Example screencap (with dummy data):
2. Implementation of a background updater goroutine to keep the list up to date. The updater automatically pings the backend to look for new searches to add to the list or invalid searches to remove from the list. It is also able to update the statuses of existing searches so a user can tell if the search they are about to attach to has completed or if they will have to attach and wait.
>[!NOTE]
>This PR …
> FEAT(#1138): gwcli: upgrade attach with auto-updates and details pane

- client/types/message.go
- client/types/render.go
Per API changes for next-major, add `Messages` to several types. We currently only have a single warning we send from backend, so populate that as well.
> add Messages fields to updated types

- client/types/render.go
- client/types/search.go
- client/types/stats.go
Updates gravwell/issues#1742
This PR adds the Messages field to some missed types, and updates all types with the Messages field to encode an empty array when no messages are present.
> Add/update Messages fields for various types

- client/types/marshallers_test.go
- client/types/render.go
- client/types/stats.go
Updates https://github.com/gravwell/issues/issues/1742
This PR adds a new type that correctly wraps the `StatSet` type to match the API. 
Example output from the marshaler:
```
{
"Stats": [
{
"TS": "0000-12-31T17:00:05-06:59",
"ModuleStats": [
{
"InputCount": 1,
"OutputCount": 0,
"InputBytes": 0,
"OutputBytes": 0,
"Duration": 0,
"ScratchWritten": 0,
"Name": "test",
"Args": ""
}
]
}
],
"Messages": [
{
"ID": 1,
"Severity": "",
"Value": ""
}
]
}
```
> Add new type for searchctrl stats API

- ingesters/version/version.go
This PR addresses no specific issue:
Old Banner:
```
Version:	5.8.6
BuildDate:	2025-08-05 23:59:59
API Version:	0.9
OS:		linux amd64 [6.1.0-35-amd64] ( )
```
New Banner:
```
Version:	5.8.6
BuildDate:	2025-08-05 23:59:59
Runtime:	1.24.5
API Version:	0.9
OS:		linux amd64 [6.1.0-35-amd64] ( )
```
> drop runtime version in ingester startup banners

- client/admin.go
This PR adds the `UpdateUser` library method, allowing for updates to a user's details via a `UserDetails` object. This is analogous to the `UpdateGroup` method and is required by the CLI for setting user CBAC permissions.
This PR addresses [#1764](https://github.com/gravwell/gravwell/issues/1764).
> feat(#1764): Add UpdateUser library method
